#! /bin/bash

# Globals
script_name=$(basename "$0") # Use basename for if this script is being read through a symlink
version=$(git tag --points-at HEAD)+$(git rev-parse --short HEAD)
crontab_location="/etc/cron.d/scheduler"
crontab_header="# This file has been automatically generated by the 'scheduler' program.
# WARNING: If you don't know what you're doing, don't touch this file!"

# TODO: Actually create a --verbose option to toggle this properly!
verbose=true

print_verbose() {
  if [ "$verbose" = true ]; then
    printf "%s\n" "$1"
  fi
}

# Functions
print_help() {
  printf "%s\n" "Usage: $script_name [COMMAND]

Commands:
  --update                update the active tasks defined in \$HOME/.config/scheduler
  --run-workflow <name>   run the <name>.yml workflow in \$HOME/.config/scheduler
  --list                  list all scheduled tasks
  --help                  show this help message
  --version               show the version" 
}

print_usage_info() {
  printf "%s\n" "Use $script_name --help for program usage information"
}

# Command handlers
update() {
  # Find our crontab
  if [ ! -f "$crontab_location" ]; then
    print_verbose "Unable to find crontab file, creating a new one..."
    echo "$crontab_header" > /etc/cron.d/scheduler
  fi

  print_verbose "Clearing old crontab via "

  # Loop through our configuration files in $HOME/.config/scheduler and add them to the crontab
}

run_workflow() {
  echo "run_workflow"
}

list() {
 echo "list"
}

if [ $# -eq 0 ]; then
  printf "%s\n\n" "$script_name: need --update, --run-workflow, or --list" 1>&2
  print_usage_info 1>&2
  exit 1
fi

# Handle arguments
# --help
if [ "$1" = "--help" ]; then
  print_help;
elif [ "$1" = "--version" ]; then
  echo "$script_name"
  echo "Version: $version"
  exit 0
# --add
elif [ "$1" = "--update" ]; then
  print_verbose "Running scheduler --update..."
  update
elif [ "$1" = "--remove" ]; then
  if [ $# -lt 2 ]; then
    printf "%s" "$script_name: --remove needs <name>\n\n" 1>&2
    print_usage_info 1>&2
    exit 1
  fi
  remove-task
else
  echo ":3"
fi
