\" Header information
.Dd October 27th, 2025  \" Last updated date
.Dt scheduler 1         \" program name & man section
.Os version 1.0         \" version number

\" NAME section
.Sh NAME
.Nm scheduler
.Nd workflow scheduling system using .yaml files

\" SYNOPSIS section
.Sh SYNOPSIS
.Nm
.Op Fl v
.Bro
.Ic list
|
.Ic run-workflow Ar name
|
.Ic update
|
.Bro
.Fl h
|
.Fl -help
.Brc
|
.Bro
.Fl v
|
.Fl -version
.Brc
.Brc

\" DESCRPITION section
.Sh DESCRIPTION
.Nm
aims to provide an easy way to schedule script workflows to run on a consistent schedule using .yaml configuration files.
.Pp
Unless --help is given, one of the following commands must be present.

.Bl -tag -width Ds
.It Ic update\ 
Updates the schedule crontab using the
.Xr scheduler-workflow 5
files stored in the configuration folder.

.It Ic run-workflow Ar name
Runs the
.Xr scheduler-workflow 5
defined in the configuration folder immediately.
.Nm
.Ic update\ 
does not need to be run before this command, as this command will perform a direct search for a file
.Ar name.yaml
in the configuration folder.

.It Ic list\ 
Lists all valid 
.Xr scheduler-workflow 5
files found in the configuration directory.
.El
